install.packages(c("devtools"), repos="http://cran.rstudio.com/")
install.packages(c("sp","gdalUtils", "rgdal", "plyr","xts"), repos="http://cran.rstudio.com/")
devtools::install_github("Paradigm4/SciDBR")
devtools::install_github("flahn/scidbst")
devtools::install_github("appelmar/strucchange")
devtools::install_github("appelmar/bfast")